//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCreditCard
    {
        public int Id { get; set; }
        public string credit_card_number { get; set; }
        public string credit_card_name { get; set; }
        public string credit_card_date { get; set; }
    }
}
