//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class McDonaldsDbEntities : DbContext
    {
        public McDonaldsDbEntities()
            : base("name=McDonaldsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankCreditCard> BankCreditCards { get; set; }
        public virtual DbSet<CategoryDish> CategoryDishes { get; set; }
        public virtual DbSet<MainDish> MainDishes { get; set; }
        public virtual DbSet<OrderedFood> OrderedFoods { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
