//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderedFoods = new HashSet<OrderedFood>();
        }
    
        public int Id { get; set; }
        public decimal sum_price { get; set; }
        public System.DateTime order_date { get; set; }
        public bool eat_in { get; set; }
        public bool is_payed { get; set; }
        public string customer_first_name { get; set; }
        public string customer_last_name { get; set; }
        public int ticket_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderedFood> OrderedFoods { get; set; }
    }
}
